[build]
  command = "npm run build:all"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm run start:lambda"
  port = 9000
 

[[redirects]]
from = "/*"
to = "/index.html"
status = 200