export const BlogsData = [
    {
        Id: "1",
        title: "Electric Scooter sales data in nov 2022",
        img: "https://static.autox.com/uploads/2021/11/Ola-Electric-S1-Pro.jpg",
        description:"An electric vehicle (EV) is a type of vehicle that is powered by an electric motor, rather than a gasoline engine. EV technology has been around for over a century, but it has gained significant popularity in recent years due to concerns about climate change and air pollution. EVs are generally considered to be more environmentally friendly than gasoline-powered vehicles, as they produce zero emissions from their tailpipes and have a lower overall environmental impact during their lifecycle. They also tend to be more energy efficient, as they can convert a higher percentage of their stored energy into motion. EVs come in a variety of shapes and sizes, including cars, buses, and even airplanes.\n\n---\n\n##### November 2022 electric two-wheeler sales in India\n\n| Rank   |      Companies     |  Unit Sold |\n|:----------|:-------------:|------:|\n| 1. |  Ola Electric | 16,246 |\n| 2. |  Ampere | 12,232 |\n| 3. |  Okinawa Autotech | 9,038 |\n| 4. |  Hero Electric | 9,008 |\n| 5. |  TVS | 8,073 |\n| 6. |  Ather Energy | 7,741 |\n| 7. |  Bajaj Auto | 2,987 |\n| 8. |  Jitendra EV | 1,253 |\n| 9. |  Pure Energy | 921 |\n| 10. |  Kinetic Green Energy | 838 |\n| 11. |  Revolt | 524 |\n| 12. |  Tork Motors | 33 |\n| 13. |  Others | 7,269 |\n| 14. |  TOTAL | 76,163 |\n\n---\n\nEVs are also becoming more affordable as the technology continues to improve and become more widely available. Many automakers now offer a range of EV models at various price points, making it easier for consumers to find an electric vehicle that fits their budget.\n\nDespite these advantages, EVs do have some limitations. For example, they can take longer to charge than filling up a gas tank, and their range may be limited compared to traditional vehicles. However, as charging infrastructure improves and battery technology advances, these limitations are becoming less of an issue.\n\nOverall, electric vehicles are a promising alternative to traditional gasoline-powered vehicles. They offer numerous environmental and financial benefits and are becoming more accessible as the technology continues to evolve.\n  \n",
        date: "25 dec 2022",
        author: "Ola Electric",
        category: "Electric Scooter",
        link: "ola-electric-scooter",
    },
];
