export const BlogsData = [
  {
    Id: "1",
    title: "Electric Scooter sales data in nov 2022",
    path: "electric-scooter-sales-data-in-nov-2022",
    img: "https://images.unsplash.com/photo-1642665076339-ca50c80a44e7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    description:"An electric vehicle (EV) is a type of vehicle that is powered by an electric motor, rather than a gasoline engine. EV technology has been around for over a century, but it has gained significant popularity in recent years due to concerns about climate change and air pollution. EVs are generally considered to be more environmentally friendly than gasoline-powered vehicles, as they produce zero emissions from their tailpipes and have a lower overall environmental impact during their lifecycle.",
    date: "25 dec 2022",
    author: "Jon Snow",
    authorImg:
      "https://images.unsplash.com/photo-1515175704145-8a06ffce6b77?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=596&q=80",
    category: "Electric Scooter",
    link: "ola-electric-scooter",
  },
  {
    Id: "2",
    title: "Why electric scooter is better than petrol scooter",
    path: "why-electric-scooter-is-better-than-petrol-scooter",
    img: "https://images.unsplash.com/photo-1566936737687-8f392a237b8b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    description:"Electric scooters are becoming an increasingly popular transportation option due to their convenience, cost-effectiveness, and environmental benefits. When compared to petrol scooters, electric scooters offer many advantages that make them a better choice for many people.",
    date: "04 jan 2023",
    author: "Jon Snow",
    authorImg:
      "https://images.unsplash.com/photo-1515175704145-8a06ffce6b77?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=596&q=80",
    category: "Electric Scooter",
    link: "electric-scooter-vs-petrol-scooter",
  },
  {
    Id: "3",
    title: "Ather 450x free non copyright images download 2023",
    path: "ather-450x-free-non-copyright-images-download-2023",
    img: "https://images.unsplash.com/photo-1624609083513-2ce2a93af609?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    description:"An extensive and free collection of images of the Ather 450x electric scooter is available to be used for various purposes. Whether it is for personal use, a website, or even for commercial use, you can find an image in this collection that will suit your needs. With its vast selection, you can find an image that will make your project stand out from the rest.",
    date: "07 jan 2023",
    author: "Alex Guill",
    authorImg:"https://images.unsplash.com/photo-1552915170-73c2330ae617?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
    category: "Electric Scooter",
    link: "how-to-choose-the-best-electric-scooter",
  },
];
